tesseract:
  datapath: ${TESSERACT_DATAPATH:/usr/share/tessdata}

spring:
  profiles:
    active: default

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.springframework.web: INFO
    org.springframework.web.multipart: DEBUG
    org.apache.coyote.http11: INFO
    com.nppang.backend: DEBUG
    root: INFO

firebase:
  service-account-source: ${FIREBASE_CREDENTIALS_JSON:file:local-placeholder}
  database-url: ${FIREBASE_DATABASE_URL:https://bookcycle-e8d43-default-rtdb.firebaseio.com/}
