tesseract:
  datapath: ${TESSERACT_DATAPATH:/usr/share/tessdata}

spring:
  profiles:
#    active: default
    active: local

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.springframework.web: INFO
    org.springframework.web.multipart: DEBUG
    org.apache.coyote.http11: INFO
    com.nppang.backend: DEBUG
    root: INFO

firebase:
  database-url: ${FIREBASE_DATABASE_URL}
  service-account-source: ${FIREBASE_SERVICE_ACCOUNT_KEY}

# JWT (JSON Web Token) 공용 설정
jwt:
  expiration-ms: 86400000 # 24시간 (1일)