spring:
  profiles:
    active: default

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.springframework.web: INFO
    org.springframework.web.multipart: DEBUG
    org.apache.coyote.http11: INFO
    com.nppang.backend: DEBUG
    root: INFO

tesseract:
  datapath: /usr/share/tessdata

firebase:
  service-account-source: ${FIREBASE_SERVICE_ACCOUNT_BASE64}
  database-url: ${FIREBASE_DATABASE_URL}


